[package]
name = "sigil"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
env_logger = "0.11.8"
lyon = "1.0.16"
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
